version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18.x
    commands:
      - cd client
      - npm install --legacy-peer-deps || exit 1

  build:
    commands:
      - npm run build

artifacts:
  base-directory: client/build
  files:
    - "**/*"
